spring.application.name=auth-service

# Fix Swagger 2.8.16 + Spring 6.2 
#spring.mvc.pathmatch.matching-strategy=ant_path_matcher

# Swagger - OpenApi
#springdoc.swagger-ui.path=/swagger-ui.html
#springdoc.api-docs.path=/v3/api-docs
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

server.forward-headers-strategy=framework
