spring.application.name=auth-service

# Fix Swagger + Spring 6.2
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

# Swagger
springdoc.swagger-ui.path=/swagger-ui
springdoc.api-docs.path=/v3/api-docs
