spring:
  application:
    name: gateway-service
  cloud:
    config:
      discovery:
        serviceId: config-server
        enabled: true
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: health,info

  info:
    env:
      enabled: true

info:
  app:
    name: gateway-service
    description: API Gateway for routing and securing microservices requests
    version: 1.0.0
