spring:
  application:
    name: gateway-service
  cloud:
    config:
      discovery:
        serviceId: config-server
        enabled: true
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: user-service-swagger
          uri: lb://user-service
          predicates:
            - Path=/users/v3/api-docs
          filters:
            - StripPrefix=1
        - id: auth-service-swagger
          uri: lb://auth-service
          predicates:
            - Path=/auth/v3/api-docs
          filters:
            - StripPrefix=1

server:
  port: 8083

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: user-service
        url: /users/v3/api-docs
      - name: auth-service
        url: /auth/v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: health,info

  info:
    env:
      enabled: true

info:
  app:
    name: gateway-service
    description: API Gateway for routing and securing microservices requests
    version: 1.0.0

eureka:
  instance:
    hostname: localhost

# JWT - https://asecuritysite.com/encryption/plain - key size 256 bit
jwt:
 secret: 7441a49f0df6460fe8ca5b70eeff5caaf31f828c5dd417942c83d762036e7ea3
