spring:
 application:
   name: gateway-service
 cloud:
  config:
   discovery:
    serviceId: config-server
    enabled: true
  gateway:
   routes:
    - id: user-service
      uri: lb://user-service
      predicates:
       - Path=/users
    - id: auth-service
      uri: lb://auth-service
      predicates:
       - Path=/auth

server:
 port: 8083

